# Generated by Django 5.1.5 on 2025-07-31 13:45

from django.db import migrations


def create_default_campuses(apps, schema_editor):
    Campus = apps.get_model('exams', 'Campus')
    campus_names = [
        'THIKA CAMPUS',
        'NAIROBI CAMPUS', 
        'NAKURU CAMPUS',
        'MOMBASA CAMPUS',
        'ELDORET CAMPUS'
    ]
    for name in campus_names:
        Campus.objects.get_or_create(name=name)


def reverse_create_default_campuses(apps, schema_editor):
    Campus = apps.get_model('exams', 'Campus')
    campus_names = [
        'THIKA CAMPUS',
        'NAIROBI CAMPUS', 
        'NAKURU CAMPUS',
        'MOMBASA CAMPUS',
        'ELDORET CAMPUS'
    ]
    Campus.objects.filter(name__in=campus_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_campuses, reverse_create_default_campuses),
    ]
