# Generated by Django 5.1.5 on 2025-07-31 17:10

from django.db import migrations


def set_default_campus_passwords(apps, schema_editor):
    Campus = apps.get_model('exams', 'Campus')
    CampusPassword = apps.get_model('exams', 'CampusPassword')
    
    # Set default passwords for each campus
    campus_passwords = {
        'THIKA CAMPUS': 'thika123',
        'NAIROBI CAMPUS': 'nairobi123', 
        'NAKURU CAMPUS': 'nakuru123',
        'MOMBASA CAMPUS': 'mombasa123',
        'ELDORET CAMPUS': 'eldoret123'
    }
    
    for campus_name, password in campus_passwords.items():
        try:
            campus = Campus.objects.get(name=campus_name)
            campus_password, created = CampusPassword.objects.get_or_create(campus=campus)
            campus_password.password = password
            campus_password.save()
            print(f'Set password for {campus_name}: {password}')
        except Campus.objects.DoesNotExist:
            print(f'Campus {campus_name} not found')


def reverse_set_default_campus_passwords(apps, schema_editor):
    CampusPassword = apps.get_model('exams', 'CampusPassword')
    CampusPassword.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_create_default_campuses'),
    ]

    operations = [
        migrations.RunPython(set_default_campus_passwords, reverse_set_default_campus_passwords),
    ]
