# Generated by Django 5.1.5 on 2025-07-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_set_default_campus_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
