# Generated by Django 5.2.4 on 2025-08-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_student_address_student_email_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
