# Generated by Django 5.2.4 on 2025-08-04 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_remove_student_address_remove_student_email_and_more'),
        ('exams', '0007_add_school_model'),  # Now depends on the School model migration
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(
                to='exams.school',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='courses',
                null=True,
                blank=True
            ),
        ),
    ]
