# Generated by Django 5.2.4 on 2025-08-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_course_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='campus',
        ),
    ]
