# Generated by Django 5.2.4 on 2025-08-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_remove_unit_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='campus',
        ),
    ]
