# Generated by Django 5.2.4 on 2025-08-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_remove_student_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examrecord',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='level',
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='school',
        ),
    ]
