# Generated by Django 5.2.4 on 2025-08-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_course_name_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('name', 'campus')},
        ),
    ]
